<SummaryScreen>:
    BoxLayout:
        orientation: 'vertical'
        padding: 10
        spacing: 10
        Label:
            text: 'Hier sollten alle gemessenen Filter Aufgelistet sein'
            
        CustButton:
            text: 'Zurück'
            size_hint: 1, 0.15
            on_press:
                root.manager.transition.direction = 'right'
                root.manager.transition.duration = 0.25
                root.manager.current = 'startscreen'